# Generated by Django 2.2.7 on 2019-11-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('author1', models.CharField(max_length=30)),
                ('author2', models.CharField(max_length=30, null=True)),
                ('publisher', models.CharField(max_length=70)),
                ('tags1', models.CharField(max_length=30)),
                ('tags2', models.CharField(max_length=30)),
                ('tags3', models.CharField(max_length=30)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
