# Generated by Django 2.2.7 on 2019-11-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_bookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='uploaded_by',
            field=models.CharField(default='DEFAULT', max_length=150),
        ),
    ]
