# Generated by Django 2.2.7 on 2019-12-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_sendmessagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessagemodel',
            name='pdffile',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
