# Generated by Django 2.2.7 on 2019-12-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_auto_20191202_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserform',
            name='emailid',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
        ),
    ]
