# Generated by Django 2.2.7 on 2019-12-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0009_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.CharField(default='abcd', max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default='abcd', max_length=150),
        ),
    ]
